
spring:
  datasource:
    url: jdbc:mariadb://localhost:3326/apidb
    username: root
    password: 123456

# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

kr:
  chis:
    jwt:
      secret: myjwtKey
      token-life-time: 600
